Repository GSG-G13/MenuMingle, pull requests merged in 2023-06, with the labels that each got.

#5 file structure
  .env.example
  .eslintrc.json
  .github/workflows/github-actions-demo.yml
  .husky/commit-msg
  .husky/pre-commit
  .vscode/settings.json
  client/.eslintrc.json
  client/.gitignore
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/vite.svg
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/components/index.ts
  client/src/hocks/index.ts
  client/src/index.css
  client/src/main.tsx
  client/src/pages/index.ts
  client/src/utils/index.ts
  client/src/utils/interfaces/index.ts
  client/src/utils/validations/index.ts
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  commitlint.config.js
  package-lock.json
  package.json
  server/__test__/test.js
  server/app.ts
  server/config/index.ts
  server/controllers/index.ts
  server/db/index.ts
  server/index.ts
  server/middleware/index.ts
  server/modles/index.ts
  server/queries/index.ts
  server/routes/index.ts
  server/utils/index.ts
  tsconfig.json
Labels: approved

#8 Dishes and categories models with seed data
  .eslintrc.json
  .husky/pre-commit
  package.json
  server/db/seed.ts
  server/db/seedData/categorySeedData.ts
  server/db/seedData/dishSeedData.ts
  server/db/seedData/index.ts
  server/models/categories.ts
  server/models/dishes.ts
  server/models/index.ts
  server/utils/types/categoriesAttributes.ts
  server/utils/types/dishesAttributes.ts
  server/utils/types/index.ts
Labels: awaiting-review

#15 6 create models moo
  server/db/seedData/rolesSeed.ts
  server/models/cart.ts
  server/models/customers.ts
  server/models/order.ts
  server/models/roles.ts
  server/models/staff.ts
  server/modules/index.ts
  server/utils/types/cart.ts
  server/utils/types/categoriesAttributes.ts
  server/utils/types/dishesAttributes.ts
  server/utils/types/index.ts
  server/utils/types/order.ts
  server/utils/types/roles.ts
Labels: awaiting-review

#16 custmer and staff and their interfacess
  server/db/seed.ts
  server/db/seedData/customersSeedData.ts
  server/db/seedData/staffSeedData.ts
  server/models/customers.ts
  server/models/index.ts
  server/models/staff.ts
  server/utils/types/cutomersAttributes.ts
  server/utils/types/stuffAttributes.ts
Labels: awaiting-review

#20 add the server error client error custome error
  package-lock.json
  package.json
  server/middleware/clientError.ts
  server/middleware/serverError.ts
  server/utils/enum/StatusCodes.ts
  server/utils/enum/index.ts
  server/utils/helper/customError.ts
  server/utils/index.ts
Labels: approved

#23 feat: readme file
  README.md
  img/Payment Method Page (radio active).png
  img/Payment done.png
  img/SplashScreen.png
  img/cart.png
  img/dashboard.png
  img/done.png
  img/done2.png
  img/emptycart.png
  img/kitchen.png
  img/login.png
  img/menu.png
  img/pending.png
  img/schema.png
  img/signup1.png
Labels: awaiting-review

#24 feat: build file
  server/db/build.ts
Labels: request-change

#26 feat: Associations
  server/models/index.ts
Labels: awaiting-review

#35 fix: refactor database and associations
  package.json
  server/db/build.ts
  server/db/config/connection.ts
  server/db/seed.ts
  server/db/seedData/customersSeedData.ts
  server/db/seedData/dishSeedData.ts
  server/db/seedData/index.ts
  server/db/seedData/rolesSeed.ts
  server/db/seedData/staffSeedData.ts
  server/models/cart.ts
  server/models/categories.ts
  server/models/customers.ts
  server/models/dishes.ts
  server/models/index.ts
  server/models/order.ts
  server/models/roles.ts
  server/models/staff.ts
  server/utils/types/cart.ts
  server/utils/types/customersAttributes.ts
  server/utils/types/dishesAttributes.ts
  server/utils/types/index.ts
  server/utils/types/order.ts
  server/utils/types/roles.ts
  server/utils/types/staffAttributes.ts
  server/utils/types/stuffAttributes.ts
Labels: merged

#30 21 backend signup
  .github/workflows/github-actions-demo.yml
  jest.config.ts
  package-lock.json
  package.json
  server/__test__/singup.test.ts
  server/__test__/test.js
  server/app.ts
  server/controllers/auth/index.ts
  server/controllers/auth/signup.ts
  server/controllers/index.ts
  server/db/build.ts
  server/db/connection.ts
  server/db/index.ts
  server/db/seed.ts
  server/db/seedData/dishSeedData.ts
  server/db/seedData/index.ts
  server/db/seedData/roles.ts
  server/index.ts
  server/middleware/serverError.ts
  server/models/cart.ts
  server/models/categories.ts
  server/models/customers.ts
  server/models/dishes.ts
  server/models/index.ts
  server/models/order.ts
  server/models/roles.ts
  server/models/staff.ts
  server/routes/auth.ts
  server/routes/index.ts
  server/utils/helper/bcrypt.ts
  server/utils/helper/index.ts
  server/utils/helper/jwt.ts
  server/utils/index.ts
  server/utils/types/index.ts
  server/utils/types/payload.ts
  server/utils/types/roles.ts
  server/utils/types/staffAttributes.ts
  server/utils/validations/joi.ts
  tsconfig.json
Labels: awaiting-review

#40 feat: add the login controller
  package.json
  server/__test__/login.test.ts
  server/__test__/singup.test.ts
  server/controllers/auth/index.ts
  server/controllers/auth/login.ts
  server/controllers/auth/signup.ts
  server/db/connection.ts
  server/db/seed.ts
  server/db/seedData/dishSeedData.ts
  server/routes/auth.ts
  server/utils/index.ts
  server/utils/validations/joi.ts
Labels: approved

#37 Created Login and Signup pages
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/assets/signupbg.png
  client/src/components/BasicSelect.tsx
  client/src/components/CopyRight.tsx
  client/src/components/index.ts
  client/src/index.css
  client/src/main.tsx
  client/src/pages/Login.tsx
  client/src/pages/SignUp.tsx
  client/src/pages/index.ts
  client/src/utils/validations/index.ts
  client/src/utils/validations/joi.ts
  package-lock.json
  package.json
Labels: awaiting-review

#38 feat: create, update, delete, getAll, dishes
  .vscode/settings.json
  client/.gitignore
  server/__test__/dishes.test.ts
  server/controllers/dishes/createDish.ts
  server/controllers/dishes/deleteDish.ts
  server/controllers/dishes/getAllDishes.ts
  server/controllers/dishes/getDishById.ts
  server/controllers/dishes/updateDish.ts
  server/controllers/index.ts
  server/middleware/clientError.ts
  server/middleware/serverError.ts
  server/routes/dishes.ts
  server/routes/index.ts
  server/utils/index.ts
  server/utils/validations/joi.ts
Labels: approved

#43 feat: splash
  client/src/App.tsx
  client/src/assets/logo.png
  client/src/pages/SplashPage/Splash.tsx
  client/src/pages/SplashPage/SplashPage.css
Labels: awaiting-review

#47 46 check auth middleware
  server/__test__/dishes.test.ts
  server/controllers/auth/logout.ts
  server/controllers/dishes/createDish.ts
  server/controllers/index.ts
  server/middleware/authMiddileware.ts
  server/middleware/index.ts
  server/routes/auth.ts
  server/routes/dishes.ts
  server/utils/index.ts
  server/utils/types/authInterface.ts
  server/utils/types/index.ts
  server/utils/validations/joi.ts
Labels: approved

#50 feat: add seedData dishes
  server/db/seedData/dishSeedData.ts
Labels: awaiting-review

#45 41 cart component
  client/.eslintrc.json
  client/package-lock.json
  client/src/App.tsx
  client/src/assets/NDPBK-d-03M.png
  client/src/assets/wallpaperflare.com_wallpaper (5).jpg
  client/src/components/cartComponent/AllCart.tsx
  client/src/components/cartComponent/ButtonSection.tsx
  client/src/components/cartComponent/CartNavBar.tsx
  client/src/components/cartComponent/DownComponet.tsx
  client/src/components/cartComponent/FoodSection.tsx
  client/src/components/cartComponent/LiftComponent.tsx
  client/src/components/cartComponent/MiddleComponent.tsx
  client/src/components/cartComponent/index.ts
  client/src/pages/CartPage.tsx
  client/src/utils/index.ts
  client/src/utils/interfaces/AllCartProps.ts
  client/src/utils/interfaces/ButtonSectionProps.ts
  client/src/utils/interfaces/DishType.ts
  client/src/utils/interfaces/FoodSectionProps.ts
  client/src/utils/interfaces/index.ts
  package-lock.json
  package.json
Labels: awaiting-review

#44 36 menu
  .vscode/settings.json
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Menu/Nav.tsx
  client/src/components/Menu/addToCart.tsx
  client/src/components/Menu/dish.tsx
  client/src/components/Menu/dishList.tsx
  client/src/components/Menu/filter.tsx
  client/src/main.tsx
  client/src/pages/Menu.tsx
  client/src/utils/interfaces/index.ts
  package-lock.json
  server/db/seedData/categorySeedData.ts
Labels: approved

#52 feat: make a socket connection
  client/package-lock.json
  client/src/App.tsx
  client/src/pages/SignUp.tsx
  package-lock.json
  package.json
  server/index.ts
  server/websocket/index.ts
Labels: awaiting-review

#54 feat: add the wating room componet
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/Group 17388.png
  client/src/assets/Group 17401.png
  client/src/assets/wallpaperflare.com_wallpaper (5).jpg
  client/src/components/cartComponent/FoodSection.tsx
  client/src/components/watingRoomComponent/Picture.tsx
  client/src/components/watingRoomComponent/Status.tsx
  client/src/pages/WatingRoom.tsx
Labels: approved

#57 feat: add to cart controller has been added
  package-lock.json
  server/controllers/cart/addToCart.ts
  server/models/cart.ts
  server/models/customers.ts
  server/models/index.ts
  server/models/order.ts
  server/routes/cart.ts
  server/routes/index.ts
  server/utils/enum/CartStatus.ts
  server/utils/enum/index.ts
  server/utils/index.ts
  server/utils/types/cart.ts
  server/utils/types/order.ts
  server/utils/validations/joi.ts
Labels: awaiting-review

#60 59 fix issues
  .env.example
  .gitignore
  client/.env.example
  client/.gitignore
  client/package-lock.json
  client/src/App.tsx
  client/src/components/Cart/CartList.tsx
  client/src/components/cartComponent/FoodSection.tsx
  client/src/pages/WatingRoom.tsx
  package-lock.json
Labels: awaiting-review

#64 send request to add to cart contrllor
  client/src/components/Cart/CartList.tsx
  client/src/components/Cart/DownComponet.tsx
  client/src/components/Cart/Pop.tsx
  client/src/index.css
  client/src/pages/Cart.tsx
  client/src/pages/Login.tsx
  server/controllers/cart/addToCart.ts
Labels: request-change

#67 feat: cook page design
  client/package-lock.json
  client/src/App.tsx
  client/src/assets/pg.png
  client/src/components/Cook/Done.tsx
  client/src/components/Cook/InProgress.tsx
  client/src/components/Cook/Incoming.tsx
  client/src/components/Cook/Nav.tsx
  client/src/pages/Cook.tsx
Labels: awaiting-review
